# 객체명 = open('경로/파일명', '파일열기모드')
# f.함수()

# 파일을 열다.(선택한 모드에 따라 동작이 상이하다) 
# 파일을 생성하다.(파일열기모드 'w')
# f = open('C:/rokey/ch12/file1.txt', 'w')
f = open('./ch12/file1.txt', 'w')
# f = open('C:/rokey/ch12/file1.txt', 'r')
# f = open('C:/rokey/ch12/file1.txt', 'a')
f.close()